#!/bin/bash -e

if [ "${LOG_TO_STDOUT}" != "1" ]; then
  mkdir -p /var/log/mongod
  chown nobody:nogroup /var/log/mongod

  exec chpst -u nobody:nogroup svlogd -tt /var/log/mongod
else
  exec chpst -u nobody:nogroup regex2json "^\\s*(?:(?P<t___time__ISO8601Milli___optional>\\S+?)\\s+\\[(?P<ctx___optional>\\S+?)\\]\\s+)?(?P<msg>.+?)\\s*$"
fi
