#!/bin/bash -e

if [ "${LOG_TO_STDOUT}" != "1" ]; then
  mkdir -p /var/log/mongod
  chown nobody:nogroup /var/log/mongod

  exec chpst -u nobody:nogroup svlogd -tt /var/log/mongod
else
  exec chpst -u nobody:nogroup regex2json "^\\s*(?P<t___time__RFC3339Milli>\\S+?)\\s+(?P<s>\\S+?)\\s+(?P<c>\\S+?)\\s+\\[(?P<ctx>\\S+?)\\]\\s+(?P<msg>.+?)\\s*$"
fi
